version: '3.10'
services:
  s_media_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
      - "/storages:/storages"
      - /tmp/s_media_service:/tmp/s_media_service
    environment:
      DATABASE_URI: postgresql://postgres:postgres@db:5432/s_media_service
    depends_on:
      - db
      - migrations
    restart: always

  db:
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: s_media_service
    restart: always

  migrations:
    build:
      context: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head'
    restart: "no"
    environment:
      DATABASE_URI: postgresql://postgres:postgres@db:5432/s_media_service
    depends_on:
      - db
