"""Added is_public to storages

Revision ID: d3603d0dd6ba
Revises: fcc40dc30138
Create Date: 2024-02-01 09:48:30.848325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3603d0dd6ba'
down_revision: Union[str, None] = 'fcc40dc30138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_statistic',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('storage_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('files_count', sa.Integer(), nullable=False),
    sa.Column('folders_count', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Record creation time'),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_storage_statistic_path_created_at', 'storage_statistic', ['path', sa.text('created_at DESC')], unique=False)
    op.add_column('storages', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storages', 'is_public')
    op.drop_index('idx_storage_statistic_path_created_at', table_name='storage_statistic')
    op.drop_table('storage_statistic')
    # ### end Alembic commands ###
