"""Add can_add field

Revision ID: eaa9f66b603d
Revises: 2dbbe08c0a1e
Create Date: 2026-01-02 13:27:01.030992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa9f66b603d'
down_revision: Union[str, None] = '2dbbe08c0a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storages', sa.Column('can_add', sa.Boolean(), nullable=True))
    # op.create_unique_constraint(None, 'storages', ['id'])
    # op.create_unique_constraint(None, 'tags', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'tags', type_='unique')
    # op.drop_constraint(None, 'storages', type_='unique')
    op.drop_column('storages', 'can_add')
    # ### end Alembic commands ###
